# Apresentação dos resultados - Processamento Paralelo

## Importando pacotes

In [1]:
import numpy as np
import pandas as pd

## Recuperando dataset

In [2]:
results_df: pd.DataFrame = pd.read_csv("data/results.csv")

## Testes

In [3]:
results_df.head(10)

   interacao     tempo  threshold   nome_modo  valor_modo       Fab
0          1  9.736030        0.5  sequencial         NaN       NaN
1          2  9.643935        0.5  sequencial         NaN       NaN
2          3  9.603937        0.5  sequencial         NaN       NaN
3          4  9.587112        0.5  sequencial         NaN       NaN
4          5  9.576417        0.5  sequencial         NaN       NaN
5          1  9.357284        0.5      static         4.0  0.042254
6          2  9.478352        0.5      static         4.0  0.042254
7          3  9.431457        0.5      static         4.0  0.042254
8          4  9.374154        0.5      static         4.0  0.042254
9          5  9.431161        0.5      static         4.0  0.042254

In [4]:
results_df["nome_modo"].unique()

<StringArray>
['sequencial', 'static', 'dynamic', 'guided']
Length: 4, dtype: str

In [5]:
results_df["valor_modo"].unique()

array([nan,  4.,  1.,  2.,  8., 16.])

In [6]:
results_df["valor_modo"].isna().sum()

5

In [7]:
results_df["Fab"].isna().sum()

5

In [8]:
results_df["interacao"] = results_df["interacao"].astype(np.uint8)
results_df["tempo"] = results_df["tempo"].astype(np.float32)
results_df["threshold"] = results_df["threshold"].astype(np.float32)
results_df["nome_modo"] = results_df["nome_modo"].astype("category")
results_df["valor_modo"] = results_df["valor_modo"].fillna(0).astype(np.uint8)
results_df["valor_modo"] = results_df["valor_modo"].astype("category")
results_df["Fab"] = results_df["Fab"].astype(np.float64)

### Sequencial

In [9]:
sequencial_df: pd.DataFrame = results_df[results_df["nome_modo"] == "sequencial"]
sequencial_df.head()

   interacao     tempo  threshold   nome_modo valor_modo  Fab
0          1  9.736030        0.5  sequencial          0  NaN
1          2  9.643935        0.5  sequencial          0  NaN
2          3  9.603937        0.5  sequencial          0  NaN
3          4  9.587112        0.5  sequencial          0  NaN
4          5  9.576417        0.5  sequencial          0  NaN

#### Tempo de execução

In [10]:
print("TEMPO")
print("Média:", sequencial_df["tempo"].mean())
print("Desvio padrão:", sequencial_df["tempo"].std())
print("Valor mínimo:", sequencial_df["tempo"].min())
print("Valor máximo:", sequencial_df["tempo"].max())

TEMPO
Média: 9.629486
Desvio padrão: 0.064855434
Valor mínimo: 9.576417
Valor máximo: 9.73603

### Static, 4

In [11]:
static_df: pd.DataFrame = results_df[results_df["nome_modo"] == "static"]
static_df.head()

   interacao     tempo  threshold nome_modo valor_modo       Fab
5          1  9.357284        0.5    static          4  0.042254
6          2  9.478352        0.5    static          4  0.042254
7          3  9.431457        0.5    static          4  0.042254
8          4  9.374154        0.5    static          4  0.042254
9          5  9.431161        0.5    static          4  0.042254

#### Tempo de execução

In [12]:
print("TEMPO")
print("Média:", static_df["tempo"].mean())
print("Desvio padrão:", static_df["tempo"].std())
print("Valor mínimo:", static_df["tempo"].min())
print("Valor máximo:", static_df["tempo"].max())

TEMPO
Média: 9.414481
Desvio padrão: 0.04884579
Valor mínimo: 9.357284
Valor máximo: 9.478352

#### Fator de balanceamento de carga (Fab)

In [13]:
print("Fab")
print("Média:", static_df["Fab"].mean())
print("Desvio padrão:", static_df["Fab"].std())
print("Valor mínimo:", static_df["Fab"].min())
print("Valor máximo:", static_df["Fab"].max())

Fab
Média: 0.04225352
Desvio padrão: 0.0
Valor mínimo: 0.04225352
Valor máximo: 0.04225352

### Dynamic, 4

In [14]:
dynamic_df: pd.DataFrame = results_df[results_df["nome_modo"] == "dynamic"]
dynamic_df.head()

    interacao     tempo  threshold nome_modo valor_modo       Fab
10          1  9.373476        0.5   dynamic          4  0.418605
11          2  9.425068        0.5   dynamic          4  0.458333
12          3  9.420016        0.5   dynamic          4  0.307692
13          4  9.474835        0.5   dynamic          4  0.512821
14          5  9.431231        0.5   dynamic          4  0.500000

#### Tempo de execução

In [15]:
print("TEMPO")
print("Média:", dynamic_df["tempo"].mean())
print("Desvio padrão:", dynamic_df["tempo"].std())
print("Valor mínimo:", dynamic_df["tempo"].min())
print("Valor máximo:", dynamic_df["tempo"].max())

TEMPO
Média: 9.424925
Desvio padrão: 0.03606217
Valor mínimo: 9.373476
Valor máximo: 9.474835

#### Fator de balanceamento de carga (Fab)

In [16]:
print("Fab")
print("Média:", dynamic_df["Fab"].mean())
print("Desvio padrão:", dynamic_df["Fab"].std())
print("Valor mínimo:", dynamic_df["Fab"].min())
print("Valor máximo:", dynamic_df["Fab"].max())

Fab
Média: 0.43949015999999996
Desvio padrão: 0.08246320970011352
Valor mínimo: 0.30769231
Valor máximo: 0.51282051

### Guided, 1

In [17]:
guided_df: pd.DataFrame = results_df.query("nome_modo == 'guided' and valor_modo == 1").copy()
guided_df.head()

    interacao      tempo  threshold nome_modo valor_modo       Fab
20          1   9.396616        0.5    guided          1  0.060606
21          2   9.536132        0.5    guided          1  0.372781
22          3   9.445127        0.5    guided          1  0.409938
23          4  11.499469        0.5    guided          1  0.371257
24          5   9.469010        0.5    guided          1  0.491429

#### Tempo de execução

In [18]:
print("TEMPO")
print("Média:", guided_df["tempo"].mean())
print("Desvio padrão:", guided_df["tempo"].std())
print("Valor mínimo:", guided_df["tempo"].min())
print("Valor máximo:", guided_df["tempo"].max())

TEMPO
Média: 9.86927
Desvio padrão: 0.9126933
Valor mínimo: 9.396616
Valor máximo: 11.499469

#### Fator de balanceamento de carga (Fab)

In [19]:
print("Fab")
print("Média:", guided_df["Fab"].mean())
print("Desvio padrão:", guided_df["Fab"].std())
print("Valor mínimo:", guided_df["Fab"].min())
print("Valor máximo:", guided_df["Fab"].max())

Fab
Média: 0.34120219800000007
Desvio padrão: 0.16426144117008826
Valor mínimo: 0.06060606
Valor máximo: 0.49142857

### Guided, 2

In [20]:
guided_df: pd.DataFrame = results_df.query("nome_modo == 'guided' and valor_modo == 2").copy()
guided_df.head()

    interacao     tempo  threshold nome_modo valor_modo       Fab
25          1  9.389120        0.5    guided          2  0.190141
26          2  9.451968        0.5    guided          2  0.417647
27          3  9.461125        0.5    guided          2  0.347561
28          4  9.496612        0.5    guided          2  0.497110
29          5  9.531858        0.5    guided          2  0.453488

#### Tempo de execução

In [21]:
print("TEMPO")
print("Média:", guided_df["tempo"].mean())
print("Desvio padrão:", guided_df["tempo"].std())
print("Valor mínimo:", guided_df["tempo"].min())
print("Valor máximo:", guided_df["tempo"].max())

TEMPO
Média: 9.466136
Desvio padrão: 0.05339823
Valor mínimo: 9.38912
Valor máximo: 9.531858

#### Fator de balanceamento de carga (Fab)

In [22]:
print("Fab")
print("Média:", guided_df["Fab"].mean())
print("Desvio padrão:", guided_df["Fab"].std())
print("Valor mínimo:", guided_df["Fab"].min())
print("Valor máximo:", guided_df["Fab"].max())

Fab
Média: 0.38118941800000006
Desvio padrão: 0.12002527568799692
Valor mínimo: 0.19014085
Valor máximo: 0.49710983

### Guided, 4

In [23]:
guided_df: pd.DataFrame = results_df.query("nome_modo == 'guided' and valor_modo == 4").copy()
guided_df.head()

    interacao     tempo  threshold nome_modo valor_modo       Fab
15          1  9.481663        0.5    guided          4  0.463415
16          2  9.484815        0.5    guided          4  0.341772
17          3  9.494643        0.5    guided          4  0.263889
18          4  9.530169        0.5    guided          4  0.263889
19          5  9.440854        0.5    guided          4  0.386667

#### Tempo de execução

In [24]:
print("TEMPO")
print("Média:", guided_df["tempo"].mean())
print("Desvio padrão:", guided_df["tempo"].std())
print("Valor mínimo:", guided_df["tempo"].min())
print("Valor máximo:", guided_df["tempo"].max())

TEMPO
Média: 9.486428
Desvio padrão: 0.031949244
Valor mínimo: 9.440854
Valor máximo: 9.530169

#### Fator de balanceamento de carga (Fab)

In [25]:
print("Fab")
print("Média:", guided_df["Fab"].mean())
print("Desvio padrão:", guided_df["Fab"].std())
print("Valor mínimo:", guided_df["Fab"].min())
print("Valor máximo:", guided_df["Fab"].max())

Fab
Média: 0.343926246
Desvio padrão: 0.08503060418924165
Valor mínimo: 0.26388889
Valor máximo: 0.46341463

### Guided, 8

In [26]:
guided_df: pd.DataFrame = results_df.query("nome_modo == 'guided' and valor_modo == 8").copy()
guided_df.head()

    interacao      tempo  threshold nome_modo valor_modo       Fab
30          1  11.572992        0.5    guided          8  0.424242
31          2   9.555800        0.5    guided          8  0.490446
32          3   9.537188        0.5    guided          8  0.464481
33          4   9.504136        0.5    guided          8  0.215827
34          5   9.516364        0.5    guided          8  0.413580

#### Tempo de execução

In [27]:
print("TEMPO")
print("Média:", guided_df["tempo"].mean())
print("Desvio padrão:", guided_df["tempo"].std())
print("Valor mínimo:", guided_df["tempo"].min())
print("Valor máximo:", guided_df["tempo"].max())

TEMPO
Média: 9.937296
Desvio padrão: 0.9145954
Valor mínimo: 9.504136
Valor máximo: 11.572992

#### Fator de balanceamento de carga (Fab)

In [28]:
print("Fab")
print("Média:", guided_df["Fab"].mean())
print("Desvio padrão:", guided_df["Fab"].std())
print("Valor mínimo:", guided_df["Fab"].min())
print("Valor máximo:", guided_df["Fab"].max())

Fab
Média: 0.401715348
Desvio padrão: 0.10841495618950077
Valor mínimo: 0.21582734
Valor máximo: 0.49044586

### Guided, 16

In [29]:
guided_df: pd.DataFrame = results_df.query("nome_modo == 'guided' and valor_modo == 16").copy()
guided_df.head()

    interacao     tempo  threshold nome_modo valor_modo       Fab
35          1  9.444173        0.5    guided         16  0.360000
36          2  9.515241        0.5    guided         16  0.204225
37          3  9.439447        0.5    guided         16  0.380952
38          4  9.461076        0.5    guided         16  0.250000
39          5  9.482745        0.5    guided         16  0.401361

#### Tempo de execução

In [30]:
print("TEMPO")
print("Média:", guided_df["tempo"].mean())
print("Desvio padrão:", guided_df["tempo"].std())
print("Valor mínimo:", guided_df["tempo"].min())
print("Valor máximo:", guided_df["tempo"].max())

TEMPO
Média: 9.468536
Desvio padrão: 0.031139165
Valor mínimo: 9.439447
Valor máximo: 9.515241

#### Fator de balanceamento de carga (Fab)

In [31]:
print("Fab")
print("Média:", guided_df["Fab"].mean())
print("Desvio padrão:", guided_df["Fab"].std())
print("Valor mínimo:", guided_df["Fab"].min())
print("Valor máximo:", guided_df["Fab"].max())

Fab
Média: 0.319307654
Desvio padrão: 0.08694265777577184
Valor mínimo: 0.20422535
Valor máximo: 0.40136054